#ifndef __VFDSTATCODES_H__
#define __VFDSTATCODES_H__

#define VFD_STATUS_SUCCESS				MAKEVFDSTATUS(SUCCESS_BIT,1)

#define VFD_STATUS_UNSUCCESSFUL			MAKEVFDSTATUS(FAILED_BIT,1)
#define VFD_STATUS_NOT_IMPLEMENTED		MAKEVFDSTATUS(FAILED_BIT,2)




#endif //__VFDSTATCODES_H__